site_name: Haplogrep 3
theme: readthedocs

nav:
- Quickstart: quickstart.md
- Getting Stared: getting-started.md
- Local Installation:
  - Installation: installation.md
  - Command-line Parameters: parameters.md
- Phylogenetic Trees:
  - Available Trees: available-trees.md
  - Installation and Usage: trees.md
- Details:
  - Input Formats: input-formats.md
  - Mutation Colouring: mutations.md
  - Annotations: annotations.md
  - Kulczynski Measure: kulczynski.md
  - Errors and Warnings: errors-warnings.md
- FAQ: faq.md
- Contact: contact.md

repo_name: genepi/haplogrep3
repo_url: https://github.com/genepi/haplogrep3
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt
      link: https://github.com/genepi/haplogrep3

markdown_extensions:
    - toc:
        permalink:
    - admonition:
    - tables
