name: Create Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Haplogrep3
        run: mvn install -B -DskipTests

      - name: Run tests
        run: mvn test -B

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "target/haplogrep3-*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
